In [1]:
import numpy as np

from functools import reduce

## Task 1

The code uses the numpy's ```intersect1d``` function that finds the intersection of 2 arrays. Since the task is to find the intersection of 3 ```ndarrays``` the code uses the ```reduce``` function from ```functools``` package. The ```reduce``` function will use the ```intersect1d``` to reduce the tuple of the 3 arrays cummulatively to reduce it to a single array containing only the values that appear in all the arrays. First the cummulative array is used to get the intersection of array a and array b then uses the result to get the intersection of the result array and array c, and stores the value in the result variable.

In [2]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
c = np.array([12, 8, 3, 7, 4, 1, 2, 9, 3, 4])

result = reduce(np.intersect1d, (a, b, c))

print("Result: ", result)

Result:  [2 4]


## Task 2

The code uses the ```arange``` function to create a 1-dimensional array which contains values from 1 to 18, since 19 will not be included in the resulting array. It then goes on to invoke the ```reshape``` function on the resulting array to make it a 3 by 6 matrix. The keyword argument (order = 'F') passed to the ```reshape``` function ensures that values are filled by column, which means the first 3 values from the 1D array appear in the first column, the second three in the next and so on, until it reaches the end.

In [3]:
arr_2d = np.arange(1, 19).reshape((3, -1), order="F" )
arr_2d

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

## Task 3

The code uses the ```ravel``` function which converts an n-dimensional array into a 1-dimensional array. By passing the keyword argument order with a value of 'F' it ensures that the values are indexed by column, which will produce the desired results 

In [4]:
arr_1d = np.ravel(arr_2d, order = "F")
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

## Task 4

The code uses the ```reshape``` function to transform the 2d array into a 3 by 3 by 2 array which is a 3d array.

In [5]:
arr_3d = arr_2d.reshape((3, 3, -1))
arr_3d

array([[[ 1,  4],
        [ 7, 10],
        [13, 16]],

       [[ 2,  5],
        [ 8, 11],
        [14, 17]],

       [[ 3,  6],
        [ 9, 12],
        [15, 18]]])

## Task 5

The code uses the ```arr_3d``` which is the 3D array created in task 4 and converts it back to a 3 by 6 2D array by invoking the ```reshape``` function on it, passing the argument (3, -1). 

In [6]:
arr_2d = arr_3d.reshape((3, -1))
arr_2d

array([[ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18]])

## Task 6

The code use ```np.union1d``` function to create an array that contains elements in array ```b``` and array ```c``` and stores the resulting array in the variable ```bc```. It then uses the ```np.delete``` function to remove all elements contained in ```bc``` but to get the indices of the elements the code use ```np.where``` as the second argument. The ```np.where``` function returns the indices of all values of ```a``` that are contained in ```bc```

In [7]:
a = np.array([12, 5, 7, 15, 3, 1, 8, 9, 2])
b = np.array([14, 2, 6, 3, 11, 19, 9, 12, 5])
c = np.array([1, 12, 4, 3, 13, 1, 9, 12, 5, 7])

bc = np.union1d(b, c)

np.delete(a, np.where(a in bc))

a

/var/folders/1k/58hcws017zn4nh_jpycwlvqw0000gn/T/ipykernel_20344/1556186884.py:7: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.delete(a, np.where(a in bc))


array([12,  5,  7, 15,  3,  1,  8,  9,  2])

## Task 7

In [8]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
# be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shown below
# with a link to the “raw” version of the file you pushed to your online GitHub repository
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/ktxdev/AIM-5001/main/M6/Module6_Data.csv').to_numpy()

# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

### Task 7a

The code uses array indexing to get all rows from the second column which contains population values and invokes the ```min``` method on the resulting array to get the minimum population, the vvalue is then stored in the variable ```min_population```. It then uses ```np.where``` function to get the index of the array with the minimum population by comparing the second column of the ```nyc_water``` array to the value contained in the variable ```min_population```. The results of the np.where function are then used to index the array to get the row that matches the results. The code goes on to calling the ```flatten``` method on the results since the result will be a 2D array. From the flettened array returned by the ```flatten``` method we take the first value which represents the year and store it in the variable ```year_with_min_population```, which is the required result.

In [9]:
min_population = nyc_water[:, 1].min()

year_with_min_population = nyc_water[np.where(nyc_water[:, 1] == min_population)].flatten()[0]

year_with_min_population

1980.0

### Task 7b

The code uses array indexing to multiply the third column values by 365 to get the total annual water consumption, it then uses the ```reshape``` function to make the resulting array a 39 by 1 matrix so it can have the same dimensions as ```nyc_water``` array and stores the result in the variable ```total_annual_water_consumption```. The code then uses the ```np.append``` function passing it the 2 arrays (```nyc_water``` and ```total_annual_water_consumption```) as positional arguments and a keyword ```axis``` with the value 1 so that it appends column-wise. The results of the ```np.append``` function are stored in the ```nyc_water``` variable

In [10]:
total_annual_water_consumption = (nyc_water[:, 2] * 365).reshape(39, 1)

nyc_water = np.append(nyc_water, total_annual_water_consumption, axis = 1)

nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ,  551880. ],
       [   1980. , 7071639. ,    1506. ,     213. ,  549690. ],
       [   1981. , 7089241. ,    1309. ,     185. ,  477785. ],
       [   1982. , 7109105. ,    1382. ,     194. ,  504430. ],
       [   1983. , 7181224. ,    1424. ,     198. ,  519760. ],
       [   1984. , 7234514. ,    1465. ,     203. ,  534725. ],
       [   1985. , 7274054. ,    1326. ,     182. ,  483990. ],
       [   1986. , 7319246. ,    1351. ,     185. ,  493115. ],
       [   1987. , 7342476. ,    1447. ,     197. ,  528155. ],
       [   1988. , 7353719. ,    1484. ,     202. ,  541660. ],
       [   1989. , 7344175. ,    1402. ,     191. ,  511730. ],
       [   1990. , 7335650. ,    1424. ,     194. ,  519760. ],
       [   1991. , 7374501. ,    1469. ,     199. ,  536185. ],
       [   1992. , 7428944. ,    1369. ,     184. ,  499685. ],
       [   1993. , 7506166. ,    1368.5,     182. ,  499502.5],
       [   1994. , 7570458. ,    1357.7,

### Task 7c

The code uses the ```np.median``` function to calculate the median of the daily water consumption by passing it the third column of ```nyc_water``` array. The next line uses the ```np.var``` function to calculate the variance of daily water consumption, passing it the 3rd column of ```nyc_water```. It then goes on to print the results using the ```print``` function.

In [11]:
median = np.median(nyc_water[:, 2])
variance = np.var(nyc_water[:, 2])

print("Median: ", median, "\nVariance: ", round(variance, 2))

Median:  1237.2 
Variance:  29744.87


### Task 7d

The code uses the np.diff function, passing the last column which represents the total annual water consumption to calculate the difference for each year except the first year. A positive value signals an increase and a negetive value signals a decrease.

In [12]:
np.diff(nyc_water[:, -1])

array([ -2190. , -71905. ,  26645. ,  15330. ,  14965. , -50735. ,
         9125. ,  35040. ,  13505. , -29930. ,   8030. ,  16425. ,
       -36500. ,   -182.5,  -3942. , -11680. , -10147. , -33726. ,
         5110. ,   6460.5,   1168. , -20586. , -17666. , -15293.5,
         2117. ,  14052.5, -25185. ,  16425. ,  -5840. , -33032.5,
        11497.5,  -6570. ,  -4343.5,  -1095. ,  -3686.5,   4745. ,
        -2555. ,  -4307. ])